name: facebook/rocksdb/jobs-macos
on: [push, pull_request]
jobs:
  build-macos:
    runs-on: macos-13
    env:
      ROCKSDB_DISABLE_JEMALLOC: 1
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 14.3.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: Run all tests
      run: ulimit -S -n `ulimit -H -n` && OPT=-DCIRCLECI make V=1 J=16 -j16 all
    - uses: "./.github/actions/post-steps"
  build-macos-cmake:
    runs-on: macos-13
    strategy:
      matrix:
        run_even_tests: [true, false]
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 14.3.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: cmake generate project file
      run: ulimit -S -n `ulimit -H -n` && mkdir build && cd build && cmake -DWITH_GFLAGS=1 ..
    - name: Build tests
      run: cd build && make V=1 -j16
    - name: Run even tests
      run: ulimit -S -n `ulimit -H -n` && cd build && ctest -j16 -I 0,,2
      if: ${{ matrix.run_even_tests }}
    - name: Run odd tests
      run: ulimit -S -n `ulimit -H -n` && cd build && ctest -j16 -I 1,,2
      if: ${{ ! matrix.run_even_tests  }}
    - uses: "./.github/actions/post-steps"

